const metrics = Object.freeze([
  {
    value: "77.55",
    label: "highest AutoPosterBench score",
    scope: "among the 14 evaluated configurations",
  },
  {
    value: "77.47",
    label: "with Claude 4.8",
    scope: "on AutoPosterBench using AutoDesign PosterHarness and Claude Code",
  },
  {
    value: "+6.79",
    label: "over Claude Design",
    scope: "same Claude Code + Claude 4.8 configuration",
  },
  {
    value: "+5.26–39.05",
    label: "improvement in matched configurations",
    scope: "across seven fixed Code Agent/model configurations on the controlled 10-paper subset",
  },
  {
    value: "100",
    label: "source papers",
    scope: "across five disciplines in AutoPosterBench",
  },
]);

const posters = Object.freeze([
  {
    slug: "attention",
    title: "Attention Is All You Need",
    discipline: "AI",
    year: "2017",
    source: "Paper · figures · tables · equations",
    format: "Editable HTML poster",
    width: 2048,
    height: 1025,
    alt: "AutoDesign poster for Attention Is All You Need",
    lead: true,
  },
  {
    slug: "videogui",
    title: "VideoGUI",
    discipline: "AI",
    year: "2024",
    source: "Paper · figures · tables",
    format: "Editable HTML poster",
    width: 2048,
    height: 1025,
    alt: "AutoDesign poster for VideoGUI",
  },
  {
    slug: "global-burden",
    title: "Global Burden of Disease",
    discipline: "Biomedicine",
    year: "2020",
    source: "Paper · quantitative figures · tables",
    format: "Editable HTML poster",
    width: 2048,
    height: 1025,
    alt: "AutoDesign poster for Global Burden of Disease",
  },
  {
    slug: "climate-projections",
    title: "Climate Change Projections",
    discipline: "Climate",
    year: "2013",
    source: "Paper · maps · figures · tables",
    format: "Editable HTML poster",
    width: 2048,
    height: 1025,
    alt: "AutoDesign poster for Climate Change Projections",
  },
  {
    slug: "currency-crashes",
    title: "Currency Crashes in Emerging Markets",
    discipline: "Economics",
    year: "1996",
    source: "Paper · charts · empirical tables",
    format: "Editable HTML poster",
    width: 2048,
    height: 1025,
    alt: "AutoDesign poster for Currency Crashes in Emerging Markets",
  },
  {
    slug: "gravitational-waves",
    title: "Observation of Gravitational Waves",
    discipline: "Physics",
    year: "2016",
    source: "Paper · detector figures · evidence",
    format: "Editable HTML poster",
    width: 2048,
    height: 1025,
    alt: "AutoDesign poster for Observation of Gravitational Waves",
  },
  {
    slug: "global-carbon-budget",
    title: "Global Carbon Budget",
    discipline: "Climate",
    year: "2020",
    source: "Paper · charts · time series",
    format: "Editable HTML poster",
    width: 2048,
    height: 1025,
    alt: "AutoDesign poster for Global Carbon Budget",
  },
  {
    slug: "vit",
    title: "An Image is Worth 16x16 Words",
    discipline: "AI",
    year: "2020",
    source: "Paper · figures · ablations",
    format: "Editable HTML poster",
    width: 2048,
    height: 1025,
    alt: "AutoDesign poster for Vision Transformer",
  },
  {
    slug: "nerf",
    title: "NeRF",
    discipline: "AI",
    year: "2020",
    source: "Paper · scene renders · architecture · metrics",
    format: "Editable HTML poster",
    width: 2048,
    height: 1025,
    alt: "Research poster for Neural Radiance Fields",
  },
  {
    slug: "clip",
    title: "Learning Transferable Visual Models",
    discipline: "AI",
    year: "2021",
    source: "Paper · zero-shot results · figures · tables",
    format: "Editable HTML poster",
    width: 2048,
    height: 1025,
    alt: "Research poster for Learning Transferable Visual Models",
  },
  {
    slug: "illustris",
    title: "The Illustris Simulation",
    discipline: "Physics",
    year: "2014",
    source: "Paper · simulation imagery · quantitative results",
    format: "Editable HTML poster",
    width: 2048,
    height: 1025,
    alt: "Research poster for the Illustris Simulation",
  },
  {
    slug: "m87",
    title: "The Shadow of a Supermassive Black Hole",
    discipline: "Physics",
    year: "2019",
    source: "Paper · telescope images · model comparisons",
    format: "Editable HTML poster",
    width: 2048,
    height: 1025,
    alt: "Research poster for the first M87 Event Horizon Telescope results",
  },
]);

const researchRecord = Object.freeze([
  ["01", "Source context", "paper text, figures, tables, and assets"],
  ["02", "Renderable artifact", "an inspectable, editable HTML poster"],
  ["03", "Diagnostic evidence", "render, validation, and evaluation traces"],
  ["04", "Candidate update", "a bounded update to PosterHarness"],
  ["05", "Accepted state", "a retained harness state for future artifacts"],
]);

const evolution = Object.freeze([
  {
    id: "00",
    phase: "Baseline",
    component: "Unoptimized production system",
    status: "observed",
    image: "evolution-00",
    title: "Observe where the artifact breaks.",
    detail: "The baseline can produce a recognizable poster, but weak visual hierarchy, uneven figure use, and large underfilled regions limit how effectively it communicates the paper. AutoDesign retains the artifact together with its diagnostic record.",
    signal: "Weak hierarchy · uneven evidence · underfilled regions",
    patch: ["capture render + DOM failures", "retain source-to-artifact provenance"],
  },
  {
    id: "01",
    phase: "Autonomous",
    component: "Context & Memory",
    status: "accepted",
    image: "evolution-01",
    title: "Restore a stable information structure.",
    detail: "The optimizer groups recurrent failures, selects the context component, and asks the Optimizer Code Agent for a bounded patch. The first autonomous state strengthens the reading path and gives visual evidence a clearer role.",
    signal: "Reading path improves · evidence becomes more visible",
    patch: ["+ rank result-bearing figures earlier", "+ preserve section-level evidence links"],
  },
  {
    id: "02",
    phase: "Autonomous",
    component: "Evaluation & Feedback",
    status: "rejected",
    image: "evolution-02",
    title: "Reject clarity that removes too much evidence.",
    detail: "The candidate is easier to scan, but large empty regions and reduced quantitative evidence expose a coverage regression. It is inspected, recorded, and rejected rather than promoted.",
    signal: "Scanning improves · information coverage falls",
    patch: ["+ simplify visual hierarchy", "- evidence density: regression"],
  },
  {
    id: "03",
    phase: "Autonomous",
    component: "Orchestration",
    status: "accepted",
    image: "evolution-03",
    title: "Turn evaluation into localized repair.",
    detail: "The accepted state combines a strong visual hierarchy with fuller source coverage. Evaluation findings are routed to affected regions while validated sections remain stable.",
    signal: "Evidence coverage rises · hierarchy stays coherent",
    patch: ["+ route issues to affected sections", "+ preserve validated regions"],
  },
  {
    id: "04",
    phase: "Final Harness",
    component: "Optimized PosterHarness",
    status: "final",
    image: "evolution-04",
    title: "Promote the strongest reusable system state.",
    detail: "The final PosterHarness balances dense paper evidence with a clear three-column reading path, native tables, prominent qualitative results, and a finished visual identity. The improvement persists for future artifacts.",
    signal: "Source-faithful · dense · readable · visually complete",
    patch: ["+ evidence-first composition", "+ stable hierarchy and bounded styling"],
  },
]);

const harnessStages = Object.freeze([
  {
    id: "01",
    name: "Context & Memory",
    short: "Context",
    summary: "Ground the design in the paper before composition begins.",
    input: "PDF · figures · tables · equations",
    output: "Paper memory · content brief · visual storyboard",
  },
  {
    id: "02",
    name: "Tools & Specifications",
    short: "Tools",
    summary: "Give the Designer an editable artifact contract and task-specific design tools.",
    input: "Poster plan · source assets · design skills",
    output: "Editable HTML and CSS",
  },
  {
    id: "03",
    name: "Execution Runtime",
    short: "Runtime",
    summary: "Run the artifact in a browser so the system can inspect what people will actually see.",
    input: "HTML · CSS · local assets",
    output: "DOM · browser render · export preview",
  },
  {
    id: "04",
    name: "Evaluation & Feedback",
    short: "Feedback",
    summary: "Combine deterministic checks with source-conditioned visual judgment.",
    input: "Render · DOM · paper evidence",
    output: "Validation issues · critic findings · repair routes",
  },
  {
    id: "05",
    name: "Orchestration",
    short: "Orchestrate",
    summary: "Manage attempts, localized revision, candidate selection, and finalization.",
    input: "Prior artifact · structured feedback",
    output: "Best valid editable poster",
  },
]);

const transferResults = Object.freeze([
  { name: "Codex / GPT-5.5", before: 41.89, after: 80.94 },
  { name: "Claude Code / Claude 4.8", before: 68.62, after: 73.88 },
  { name: "Kimi Code / Kimi K2.7", before: 46.81, after: 72.20 },
  { name: "Claude Code / Seed 2.1 Pro", before: 54.22, after: 70.58 },
  { name: "ZCode / GLM 5.2", before: 34.86, after: 68.53 },
  { name: "Claude Code / LongCat 2.0", before: 42.51, after: 54.69 },
  { name: "Claude Code / DeepSeek V4 Pro", before: 33.74, after: 54.40 },
]);

window.AutoDesignSiteData = Object.freeze({
  evolution,
  harnessStages,
  metrics,
  posters,
  researchRecord,
  transferResults,
});
